CREATE USER C##ORCLSTUDY
IDENTIFIED BY ORACLE;

ALTER SESSION SET "_oracle_script"=true;

CREATE USER ORCLSTUDY
IDENTIFIED BY ORACLE;

GRANT CREATE SESSION TO ORCLSTUDY;

ALTER USER ORCLSTUDY
IDENTIFIED BY ORCL;

DROP USER ORCLSTUDY;

DROP USER ORCLSTUDY CASCADE;

CREATE USER ORCLSTUDY
IDENTIFIED BY ORACLE
DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

GRANT RESOURCE, CREATE SESSION, CREATE TABLE TO ORCLSTUDY;

CREATE TABLE TEMP1 (
  COL1 VARCHAR2(20),
  COL2 VARCHAR2(20)
);

INSERT INTO TEMP1 VALUES ('USER', 'GRANT_TEST');

SELECT * FROM TEMP1;

REVOKE RESOURCE, CREATE TABLE FROM ORCLSTUDY;

CREATE TABLE TEMP2 (
 COL1 VARCHAR2(20),
 COL2 VARCHAR2(20)
);

CREATE TABLE TEMP(
  COL1 VARCHAR2(20),
  COL2 VARCHAR2(20)
);

GRANT SELECT ON TEMP TO ORCLSTUDY;

GRANT INSERT ON TEMP TO ORCLSTUDY;

GRANT SELECT, INSERT ON TEMP
 TO ORCLSTUDY;
 
SELECT * FROM SCOTT.TEMP;

INSERT INTO SCOTT.TEMP VALUES('TEXT', 'FROM ORCLSTUDY');

SELECT * FROM SCOTT.TEMP;

REVOKE SELECT, INSERT ON TEMP FROM ORCLSTUDY;

SELECT * FROM SCOTT.TEMP;

CREATE ROLE ROLESTUDY;

GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SYNONYM
 TO ROLESTUDY;
 
GRANT ROLESTUDY TO ORCLSTUDY;

SELECT * FROM USER_SYS_PRIVS;

SELECT * FROM USER_ROLE_PRIVS;
